import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';
import { randomUUID } from 'node:crypto';
const PUBLIC_PORT=Number(process.env.PORT||10000),UPSTREAM_PORT=10001,ROOT='/app';
const INPUT=path.join(ROOT,'input','scripts','input-scripts.json'),OUTPUT=path.join(ROOT,'output');
const jobs=new Map();
const PAGE=`<!doctype html><html lang="pt-BR"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VÍDEOCREATOR</title><style>body{font-family:Arial;max-width:760px;margin:auto;padding:18px;background:#101522;color:#fff}section{background:#1b2435;padding:18px;border-radius:16px;margin:14px 0}input,textarea,select,button{width:100%;box-sizing:border-box;padding:13px;margin:7px 0;border-radius:10px;border:0;font-size:16px}button{background:#6ee7b7;font-weight:bold}textarea{min-height:180px}a{color:#6ee7b7}.ok{color:#6ee7b7}.err{color:#ff9b9b}</style><section><h1>🎬 VÍDEOCREATOR</h1><p>Geração real de vídeo no servidor.</p><p id="health">Verificando motor...</p></section><section><h2>Novo vídeo</h2><input id="title" value="Tecnologia e Inteligência Artificial"><textarea id="script">A inteligência artificial está transformando a tecnologia e mudando a forma como trabalhamos. Neste vídeo você vai conhecer algumas aplicações incríveis da IA e descobrir como essa tecnologia está avançando rapidamente.</textarea><select id="orientation"><option value="portrait">Retrato 9:16 — Shorts</option><option value="landscape">Paisagem 16:9 — YouTube</option></select><button onclick="create()">🎬 CRIAR VÍDEO AGORA</button><p id="status"></p></section><section id="result" style="display:none"><h2>Produção</h2><p id="progress"></p><div id="link"></div></section><script>
async function check(){try{let r=await fetch('/api/health');let d=await r.json();health.innerHTML='<span class="ok">● Motor online e pronto para gerar.</span>'}catch(e){health.innerHTML='<span class="err">● Motor indisponível.</span>'}};
async function create(){let title=document.getElementById('title').value.trim(),script=document.getElementById('script').value.trim(),orientation=document.getElementById('orientation').value,s=document.getElementById('status');s.textContent='Enviando para o motor...';try{let r=await fetch('/api/jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({title,script,orientation,language:'portuguese'})});let raw=await r.text();let d;try{d=JSON.parse(raw)}catch(e){throw Error('Resposta do servidor não é JSON: '+raw.slice(0,100))}if(!r.ok)throw Error(d.error||'Falha');document.getElementById('result').style.display='block';poll(d.data.jobId);s.textContent='Produção iniciada.'}catch(e){s.innerHTML='<span class="err">'+e.message+'</span>'}};
async function poll(id){try{let r=await fetch('/api/jobs/'+id),j=await r.json(),d=j.data||j;progress.textContent=d.message||d.status;if(d.status==='completed'){link.innerHTML='<a href="'+d.videoUrl+'" target="_blank">▶ ASSISTIR / ABRIR VÍDEO</a>';return}if(d.status==='failed'){link.innerHTML='<span class="err">'+(d.errorLog||d.message)+'</span>';return}setTimeout(()=>poll(id),3000)}catch(e){setTimeout(()=>poll(id),5000)}}check();</script>`;
function json(res,code,obj){if(res.headersSent)return;const data=JSON.stringify(obj);res.writeHead(code,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(data),'access-control-allow-origin':'*'});res.end(data)}
async function readBody(req){const a=[];for await(const c of req)a.push(c);return JSON.parse(Buffer.concat(a).toString()||'{}')}
function newestMp4(dir){if(!fs.existsSync(dir))return null;const st=[dir];let best=null;while(st.length){const d=st.pop();for(const n of fs.readdirSync(d)){const f=path.join(d,n),s=fs.statSync(f);if(s.isDirectory())st.push(f);else if(n.endsWith('.mp4')&&(!best||s.mtimeMs>best.mtimeMs))best={path:f,mtimeMs:s.mtimeMs}}}return best?.path||null}
function start(job){fs.mkdirSync(path.dirname(INPUT),{recursive:true});const before=new Set();const old=newestMp4(OUTPUT);if(old)before.add(old);job.generatorId='vc_'+job.id.replaceAll('-','');fs.writeFileSync(INPUT,JSON.stringify([{id:job.generatorId,title:job.title,script:job.script,orientation:job.orientation,language:job.language,showText:true}],null,2));job.status='processing';job.message='Gerando narração, mídia, legendas e MP4...';const c=spawn('npm',['run','generate'],{cwd:ROOT,env:process.env,stdio:['ignore','pipe','pipe']});c.stdout.on('data',x=>job.log=(job.log||'')+x.toString().slice(-12000));c.stderr.on('data',x=>job.errorLog=(job.errorLog||'')+x.toString().slice(-12000));c.on('error',e=>{job.status='failed';job.message='Falha ao iniciar o motor.';job.errorLog=String(e)});c.on('close',code=>{const f=newestMp4(path.join(OUTPUT,job.generatorId))||newestMp4(OUTPUT);if(code===0&&f&&!before.has(f)){job.status='completed';job.output=f;job.videoUrl='/api/jobs/'+job.id+'/video';job.message='Vídeo concluído com sucesso.'}else{job.status='failed';job.message=code===0?'O motor terminou sem produzir um MP4 novo.':'O motor terminou com código '+code+'.';job.errorLog=job.errorLog||job.log||'Sem detalhes.'}})}
async function api(req,res){if(req.method==='GET'&&req.url==='/api/health'){json(res,200,{status:'online',engine:'Automated Video Generator',mode:'remote-worker',no_api_key_tts:true});return true}if(req.method==='POST'&&req.url==='/api/jobs'){try{const d=await readBody(req);if(!d.title||String(d.script||'').length<10){json(res,400,{error:'title e script são obrigatórios'});return true}if([...jobs.values()].some(j=>j.status==='processing')){json(res,409,{error:'Já existe uma produção em andamento.'});return true}const id=randomUUID(),j={id,title:String(d.title).slice(0,180),script:String(d.script).slice(0,5000),orientation:d.orientation==='landscape'?'landscape':'portrait',language:d.language||'portuguese',status:'queued',message:'Tarefa recebida.'};jobs.set(id,j);start(j);json(res,202,{success:true,data:{jobId:id,title:j.title,status:'processing',statusUrl:'/api/jobs/'+id}})}catch(e){json(res,400,{error:'Não foi possível receber o comando: '+e.message})}return true}const m=req.url?.match(/^\/api\/jobs\/([^/]+)(?:\/(video))?$/);if(m){const j=jobs.get(m[1]);if(!j){json(res,404,{error:'Job não encontrado.'});return true}if(m[2]==='video'){if(!j.output||!fs.existsSync(j.output)){json(res,404,{error:'Vídeo ainda não disponível.'});return true}res.writeHead(200,{'content-type':'video/mp4','content-disposition':'inline','content-length':fs.statSync(j.output).size,'access-control-allow-origin':'*'});fs.createReadStream(j.output).pipe(res);return true}json(res,200,{success:true,data:j});return true}return false}
const upstream=spawn('npm',['run','dev'],{cwd:ROOT,env:{...process.env,HOST:'127.0.0.1',PORT:String(UPSTREAM_PORT)},stdio:'inherit'});
const server=http.createServer(async(req,res)=>{try{if(req.method==='GET'&&req.url==='/'){res.writeHead(200,{'content-type':'text/html; charset=utf-8'});res.end(PAGE);return}if(req.url?.startsWith('/api/')&&await api(req,res))return;const r=await fetch('http://127.0.0.1:'+UPSTREAM_PORT+(req.url||'/'),{method:req.method,headers:req.headers,body:['GET','HEAD'].includes(req.method)?undefined:req});res.writeHead(r.status,Object.fromEntries(r.headers));if(r.body)r.body.pipeTo(new WritableStream({write(c){res.write(Buffer.from(c))},close(){res.end()}})).catch(()=>res.end());else res.end()}catch(e){json(res,502,{error:'Upstream indisponível',detail:String(e)})}});server.listen(PUBLIC_PORT,'0.0.0.0',()=>console.log('VÍDEOCREATOR listening on 0.0.0.0:'+PUBLIC_PORT));
